[[checkers]]
name = "cargo-check"
kind = "command"
command = "cargo check --message-format=json"
parser = "rustc-json"
run_on = ["*.rs"]

[[checkers]]
name = "clippy"
kind = "command"
command = "cargo clippy --message-format=json"
parser = "rustc-json"
run_on = ["*.rs"]
lint = true
